Repository UruruLab/Ururu-AI, pull requests merged in 2025-07, with the labels that each got.

#2 텍스트 임베딩 모델 설치 및 기본 API 구현
  app/api/test_embedding.py
  app/main.py
  requirements.txt
Labels: 💫 Feature

#4 TwoTower 중 User Tower 구현
  app/api/user.py
  app/core/dependencies.py
  app/main.py
  app/models/user.py
  app/services/user_tower_service.py
Labels: 💫 Feature

#6 Product Tower 기본 모델 및 설정 구현
  app/core/config.py
  app/models/__init__.py
  app/models/product.py
Labels: 💫 Feature

#14 RDB 연동
  app/api/admin.py
  app/api/product.py
  app/core/config.py
  app/core/database.py
  app/core/dependencies.py
  app/main.py
  app/models/database/__init__.py
  app/models/database/ai_models.py
  app/models/database/base.py
  app/models/database/spring_models.py
  app/models/product.py
  app/services/product_converter.py
  requirements.txt
Labels: 💫 Feature

#16 Faiss 벡터 저장소 연동 및 상품 카테고리 매핑 로직 수정
  app/api/product.py
  app/api/recommendations.py
  app/api/vector.py
  app/core/config.py
  app/core/dependencies.py
  app/main.py
  app/services/faiss_service.py
  app/services/product_converter.py
  app/services/product_tower_service.py
  app/services/recommendation_service.py
Labels: 💫 Feature

#19 GitHub Actions CI/CD 파이프라인 구축
  .github/workflows/ci-cd.yml
  .github/workflows/docker-health-check.yml
  .github/workflows/performance-test.yml
  pytest.ini
  tests/__init__.py
  tests/conftest.py
  tests/test_basic.py
Labels: 🌳 Environment, 💫 Feature

#21 GHCR 조직 패키지 푸시 권한 문제 해결 및 테스트/버그픽스 브랜치 워크플로우 자동 실행 추가
  .github/workflows/ci-cd.yml
Labels: 🌳 Environment, 🐞 Bug

#22 docker-compose 네트워크 정의 추가 및 배포 환경 구성 오류 수정
  docker-compose.production.yml
Labels: 🌳 Environment, 🐞 Bug

#23 추천 시스템 카테고리 필터링 로직 리팩토링
  app/api/recommendations.py
  app/core/dependencies.py
  app/main.py
  app/models/product.py
  app/models/recommendation.py
  app/models/user.py
  app/services/product_converter.py
  app/services/product_tower_service.py
  app/services/recommendation_service.py
Labels: 🛠️ Refactor

#26 fix: CI/CD와 Docker 설정에서 Config 레포지토리 연동 및 헬스체크 완성
  .github/workflows/ci-cd.yml
  .github/workflows/docker-health-check.yml
  .github/workflows/performance-test.yml
  docker-compose.development.yml
  docker-compose.production.yml
  docker-compose.yml
  scripts/run-dev.sh
  scripts/run-prod.sh
Labels: 🌳 Environment, 🐞 Bug

#28 Spring Boot AI 서비스 연동 502 에러 해결
  .github/workflows/ci-cd.yml
  .github/workflows/docker-health-check.yml
  .github/workflows/performance-test.yml
  app/core/config.py
  docker-compose.development.yml
  docker-compose.production.yml
  docker/Dockerfile
  docker/docker-compose-ai-prod.yml
  docker/docker-compose-ai.yml
Labels: 🌳 Environment, 🐞 Bug, 🛠️ Refactor
